export const lightColors = {
  bg: '#FAF9F6',
  cardBg: '#FFFFFF',
  cardAlt: '#F5F2EC',
  accent: '#45B8A0',
  accentLight: '#DEF3ED',
  accentDark: '#1F8571',
  textPrimary: '#2B2A28',
  textSecondary: '#7A756D',
  textMuted: '#AFA99F',
  border: '#ECE7DE',
  success: '#3FAE7A',
  successLight: '#E4F5EC',
  warning: '#E0A542',
  warningLight: '#FBF0DD',
  danger: '#E2726B',
  dangerLight: '#FBEAE8',
  // Time-of-day accents (morning / midday / evening) — pastel, not status colors
  morning: '#45B8A0',
  morningLight: '#DEF3ED',
  midday: '#8C7FD6',
  middayLight: '#EBE7FA',
  evening: '#E39A6B',
  eveningLight: '#FBEADC',
};

export const darkColors: typeof lightColors = {
  bg: '#16181B',
  cardBg: '#1F2226',
  cardAlt: '#23272C',
  accent: '#4FC7AE',
  accentLight: '#1E3A34',
  accentDark: '#84DFC9',
  textPrimary: '#F2F0EB',
  textSecondary: '#ACA89F',
  textMuted: '#6E6A63',
  border: '#2B2F34',
  success: '#4FC08A',
  successLight: '#183A2B',
  warning: '#E8B360',
  warningLight: '#3A2E14',
  danger: '#E8837A',
  dangerLight: '#3A211D',
  morning: '#4FC7AE',
  morningLight: '#1E3A34',
  midday: '#A79BEB',
  middayLight: '#2C2740',
  evening: '#E8AE80',
  eveningLight: '#3A2A1C',
};

/** @deprecated use useTheme().colors instead — kept only as the light default */
export const colors = lightColors;
